version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running the application...
      - node index.js  # Change 'index.js' to your main file

artifacts:
  files:
    - "**/*"
